### ISSUE TITLE
Question: How to restart stream?

### ISSUE THREAD

**Issue by unlight** [troch/gulp-memory-cache#1]
Let me explain what I'm trying to do.

``` js
var srcTypings = gulp.src(conf.typings)
    .pipe(g.memoryCache("typings")); // Saving to cache
```

This is my stream1, it contains known count of files and I do not want do read it every-time.

Later, I do:

``` js
    var sourceStream = merge2(
        g.memoryCache("typings"), // readable stream ended? it can only write?
        gulp.src(glob, {since: gulp.lastRun("typescript")}) // second stream
    );
```

merge2 merges my stream in sequence, but looks like stream1 do not producing data
Therefore, `second stream` never starts, and `sourceStream` never ends.

Do I need somehow to re-emit files from this cache to new stream? E.g.

``` js
var newStream = through2.obj( (chunk, enc, callback)  => {
    var cache = g.memoryCache.get("typings");
    cache.getFilePaths().map(file => {
         this.push(cache.get(file));
    })
});
```

``` js
    var sourceStream = merge2(
       newStream , // readable stream ended? it can only write?
        gulp.src(glob, {since: gulp.lastRun("typescript")}) // second stream
    );
```

Or is it possible without creating new stream?

**Comment by troch** [comment]
`g.memoryCache("typings")` is just a transformer. What you want is basically to use caches as sources?

**Comment by unlight** [comment]
Yes. I want pull files from cache to get same result as `gulp.src` 

``` js
gulp.src(conf.typings, { since: g.memoryCache.lastMtime("typings") })
    .pipe(g.memoryCache("typings"))
```

Example above works. But my goal to get rid of `gulp.src` completely.

**Comment by unlight** [comment]
I will try to use this [floatdrop/save-stream](https://github.com/floatdrop/save-stream)

**Comment by troch** [comment]
It looks like it solves your problem. If you want this functionality with `gulp-memory-cache`, feel free to open a PR.
