### ISSUE TITLE
SCSS Incremental Compilation with vendor partials

### ISSUE THREAD

**Issue by pablodenadai** [troch/gulp-memory-cache#2]
Hi Thomas, it's Pablo (from Barclays) here.

I'm implementing SCSS Incremental Compilation in my project and I came across this issue when using vendor partials and Sourcemaps.

The task runs fine at first (I believe the cache is empty at that stage). But then in the next run it throws an error.

**Error message**

`Error: "/node_modules/bootstrap/scss/_variables.scss" is not in the SourceMap.`

The file `/node_modules/bootstrap/scss/_variables.scss` lives outside the srcGlob and I'm wondering if that's what's causing the issue.

**Task**

``` js
module.exports = function scss() {
    return gulp.src('src/scss/**/*.{scss,sass}', {
        since: plugins.memoryCache.lastMtime('scss')
    })

    // Linting
    .pipe(plugins.sassLint({ config: '.sass-lint.yml' }))
    .pipe(plugins.sassLint.format())
    .pipe(plugins.sassLint.failOnError())

    // Cache
    .pipe(plugins.memoryCache('scss'))

    // Sourcemap and transpilation
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.sourcemaps.write())

    // Output
    .pipe(gulp.dest('build/css'));
};
```

**Full stack**

``` bash
C:\angular2-seed-project\node_modules\source-map\lib\source-map-consumer.js:703
        throw new Error('"' + aSource + '" is not in the SourceMap.');
        ^

Error: "/node_modules/bootstrap/scss/_variables.scss" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (C:\angular2-seed-project\node_modules\source-map\lib\source-map-consumer.js:703:15)
    at SourceMapGenerator.<anonymous> (C:\angular2-seed-project\node_modules\source-map\lib\source-map-generator.js:229:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (C:\angular2-seed-project\node_modules\source-map\lib\source-map-generator.js:228:34)
    at applySourceMap (C:\angular2-seed-project\node_modules\vinyl-sourcemaps-apply\index.js:27:15)
    at filePush (C:\angular2-seed-project\node_modules\gulp-sass\index.js:104:9)
    at Object.callback (C:\angular2-seed-project\node_modules\gulp-sass\index.js:146:9)
    at options.success (C:\angular2-seed-project\node_modules\node-sass\lib\index.js:294:32)
```

Is it something you'd be interested in supporting?

**Comment by troch** [comment]
Hi Pablo,

Have you tried removing `gulp-memory-cache` plugin? Does it work without it?

**Comment by pablodenadai** [comment]
Yes - it works fine without the `gulp-memory-cache` plugin.

**Comment by troch** [comment]
Have you tried removing the `since` but keeping the pipe transformer (so it loads everything in the stream all the time)?

Trying to understand what the issue could be

**Comment by pablodenadai** [comment]
Yes - it also works if I just remove the `since` but leave the transformer in place.

**Comment by troch** [comment]
What if you keep the `since` in place but add `/node_modules/bootstrap/scss/_variables.scss` and other relevant sources to `gulp.src`?

**Comment by pablodenadai** [comment]
Let me try that. 

FYI it works fine if I just remove the `plugins.sourcemaps.init()` and `plugins.sourcemaps.write()`.

**Comment by pablodenadai** [comment]
Same problem if I add `/node_modules/bootstrap/scss/_variables.scss` to `gulp.src`. It works the first time but fails the next.

**Comment by pablodenadai** [comment]
I'll try to get more debug info - I guess this is a edge case with partials and sourcemaps so I don't want to bother you too much.

**Comment by troch** [comment]
I'll need to investigate further, just now I can't think of what might be the issue. The order of your transformers seems logical, and the cache transformer is not manipulating individual objects.

**Comment by troch** [comment]
My first assumption was that it might be an issue with what the base path is (your glob `'src/scss/**/*.{scss,sass}'` will force it to be `src/scss`), but I don't see how it relates to the cache transformer. Maybe you can try playing with `base` (I don't give it much hope):

``` js
    return gulp.src('src/scss/**/*.{scss,sass}', {
        base: process.cwd(),
        since: plugins.memoryCache.lastMtime('scss')
    })
```

**Comment by pablodenadai** [comment]
No luck. I've also tried a combination of `gulp-cache` and `gulp-remember` but it also fails with the same error message. I guess it's something to do with SCSS partials and the sourcemaps.

I'll close it for now - I might attempt implementing incremental build again in the future.

Cheers.

**Comment by troch** [comment]
If I clone your angular seed project, is it something I can replicate?

**Comment by pablodenadai** [comment]
That'd be nice man. This is the [task](https://github.com/ghpabs/angular2-seed-project/blob/master/tasks/gulp-scss.js) that I'm working on. 

You should be able to run...

```
npm i
gulp serve
```

... and then update any `.scss` file in the `src/scss` folder.

There's no rush at all though.

**Comment by pablodenadai** [comment]
Okay I think I know what the issue is here. I only had a `function` called `scss` but I didn't have a `gulp.task` called `scss`.

Does it make sense?

**Comment by troch** [comment]
Not really lol.

**Comment by pablodenadai** [comment]
Haha nvm.
