### ISSUE TITLE
1:many

### ISSUE THREAD

**Issue by mabar** [troch/gulp-memory-cache#4]
I don't perfectly understand how cache is working in gulp stream. I need support of 1:many for caching of gulp-fontmin. Can you show me how to use it in my task? Use case of 1:many in readme would be good too.

function fontsParse(done) {
  let cssFilter = filter(["**/*", "!**/*.css"]);

  gulp.src("src/fonts/*_/_")
          .pipe(plumber())
          .pipe(fontmin())
          .pipe(cssFilter) //removing css file, keeps only fonts
          .pipe(gulp.dest("dest/fonts/"));
  reload(); //browsersync.reload
  done();
}

**Comment by S1SYPHOS** [comment]
I'd be interested in this too
